version: "3"

services:
  mysql:
    container_name: mysql-on-docker
    image: mysql:5.7
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - ./nucarpool-db-data:/var/lib/mysql

volumes:
  nucarpool-db-data:
