name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }}
            If your PR contains any changes to the schema.prisma file, please open a deploy request on 
            PlanetScale before merging. If you have any questions, ping @Luke Jianu on Slack.
